import React, { useState } from 'react';
import { Outlet } from 'react-router-dom';
import Navbar from './components/Navbar';
import './App.css';
import AnimatedOutlet from './components/AnimatedOutlet';
import Footer from './components/Footer';

function App() {
  const [showLegal, setShowLegal] = useState(false);

  const openLegalModal = () => setShowLegal(true);
  const closeLegalModal = () => setShowLegal(false);

  return (
    <div className="min-h-screen flex flex-col bg-gray-50 dark:bg-gray-900">
      <Navbar />
      <main className="flex-1">
        <AnimatedOutlet />
      </main>
      <Footer openLegalModal={openLegalModal} />
      {showLegal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-40 transition-opacity duration-300 animate-fade-in px-2">
          <div className="bg-white dark:bg-slate-800 rounded-lg shadow-lg p-4 sm:p-6 max-w-sm sm:max-w-md md:max-w-lg w-full relative transform transition-all duration-300 animate-modal-pop overflow-y-auto max-h-[90vh]">
            <button
              onClick={closeLegalModal}
              className="absolute top-2 right-2 text-slate-400 hover:text-emerald-600 text-2xl font-bold focus:outline-none focus:ring-2 focus:ring-emerald-500"
              aria-label="Close"
            >
              ×
            </button>
            <h2 className="text-lg font-semibold mb-2 text-slate-800 dark:text-slate-100 text-center">🛡️ Privacy & Terms</h2>
            <div className="text-slate-600 dark:text-slate-300 text-sm mb-2 space-y-3">
              <div><strong>Effective Date:</strong> June 26, 2025<br/><strong>Last Updated:</strong> June 26, 2025</div>
              <div>
                GlucoTrack is a personal health assistant and demo application built for educational and non-commercial purposes. We are committed to maintaining user privacy and transparency in how the app operates.
              </div>
              <div>
                <span className="font-semibold">🔒 Privacy Policy</span>
                <ul className="list-disc pl-5 mt-1">
                  <li>No Data Collection: GlucoTrack does not collect, store, or transmit any personal health data or user inputs to any external servers or third parties.</li>
                  <li>Local-only Execution: All predictions and data processing are performed locally in your browser or through a secure local API.</li>
                  <li>No Cookies or Tracking: We do not use cookies, analytics, advertising, or tracking technologies.</li>
                  <li>No Login Required: The app does not require authentication or user accounts.</li>
                </ul>
              </div>
              <div>
                <span className="font-semibold">📄 Terms of Use</span>
                <ul className="list-disc pl-5 mt-1">
                  <li>For Educational Use Only: This application is provided for demonstration and educational purposes. It is not intended to diagnose, treat, or monitor any medical condition.</li>
                  <li>No Medical Advice: Predictions and outputs generated by GlucoTrack should not be considered medical advice. Always consult with a qualified healthcare professional for health-related decisions.</li>
                  <li>No Liability: The creators of GlucoTrack are not liable for any decisions, actions, or outcomes resulting from the use of this application. Use at your own discretion.</li>
                </ul>
              </div>
              <div>
                <span className="font-semibold">🤝 Contact</span><br/>
                If you have questions, feedback, or would like to contribute, please contact the project author.
              </div>
            </div>
            <button
              onClick={closeLegalModal}
              className="mt-4 w-full sm:w-auto px-4 py-2 rounded bg-emerald-600 text-white hover:bg-emerald-700 transition-all text-sm"
            >
              Close
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

export default App
